from itertools import groupby
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModel, AutoConfig
from codes.modeljmrl import DocREModel
from codes.prepro import read_docred
import json
import os
import numpy as np
from codes.evaluation import to_official
import torch
import os
import random
import numpy as np
import nltk
from tqdm import tqdm
import argparse

ALLOWED_RELATIONS = {
    ("MATERIEL", "WAS_CREATED_IN", "TIME_EXACT"),
    ("CIVILIAN", "HAS_CONTROL_OVER", "GROUP_OF_INDIVIDUALS"),
    ("ECONOMICAL_CRISIS", "END_DATE", "TIME_EXACT"),
    ("TERRORIST_OR_CRIMINAL", "IS_OF_NATIONALITY", "NATIONALITY"),
    ("GROUP_OF_INDIVIDUALS", "IS_OF_SIZE", "QUANTITY_FUZZY"),
    ("NATURAL_EVENT", "START_DATE", "TIME_MAX"),
    ("GROUP_OF_INDIVIDUALS", "IS_COOPERATING_WITH", "MILITARY_ORGANISATION"),
    ("RIOT", "START_DATE", "TIME_MIN"),
    ("AGITATING_TROUBLE_MAKING", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("CBRN_EVENT", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("COUP_D_ETAT", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("NON_GOVERNMENTAL_ORGANISATION", "HAS_CONSEQUENCE", "HOOLIGANISM_TROUBLEMAKING"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "IS_LOCATED_IN", "PLACE"),
    ("CIVIL_WAR_OUTBREAK", "HAS_CONSEQUENCE", "CIVIL_WAR_OUTBREAK"),
    ("DEMONSTRATION", "START_DATE", "TIME_MIN"),
    ("GROUP_OF_INDIVIDUALS", "IS_OF_SIZE", "QUANTITY_MIN"),
    ("INTERGOVERNMENTAL_ORGANISATION", "IS_AT_ODDS_WITH", "GROUP_OF_INDIVIDUALS"),
    ("GROUP_OF_INDIVIDUALS", "HAS_CONTROL_OVER", "TERRORIST_OR_CRIMINAL"),
    ("CBRN_EVENT", "END_DATE", "TIME_EXACT"),
    ("PLACE", "IS_OF_NATIONALITY", "NATIONALITY"),
    ("NON_GOVERNMENTAL_ORGANISATION", "HAS_CONTROL_OVER", "CIVILIAN"),
    ("MILITARY", "GENDER_FEMALE", "MILITARY"),
    ("GATHERING", "HAS_CONSEQUENCE", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("MILITARY", "IS_BORN_IN", "PLACE"),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "FIRE"),
    ("BOMBING", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("PLACE", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_AT_ODDS_WITH", "MILITARY"),
    ("DRUG_OPERATION", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("CIVILIAN", "IS_BORN_IN", "PLACE"),
    ("CIVILIAN", "IS_LOCATED_IN", "CRIMINAL_ARREST"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "START_DATE", "TIME_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "AGITATING_TROUBLE_MAKING"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "THEFT"),
    ("GATHERING", "END_DATE", "TIME_MAX"),
    ("GROUP_OF_INDIVIDUALS", "IS_AT_ODDS_WITH", "GROUP_OF_INDIVIDUALS"),
    ("EPIDEMIC", "HAS_CONSEQUENCE", "EPIDEMIC"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "HAS_CONTROL_OVER",
        "MILITARY_ORGANISATION",
    ),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "RIOT"),
    ("CIVILIAN", "HAS_FAMILY_RELATIONSHIP", "CIVILIAN"),
    ("BOMBING", "HAS_CONSEQUENCE", "FIRE"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "END_DATE", "TIME_FUZZY"),
    ("DRUG_OPERATION", "HAS_CONSEQUENCE", "DRUG_OPERATION"),
    ("ECONOMICAL_CRISIS", "START_DATE", "TIME_FUZZY"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "DRUG_OPERATION"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "INTERGOVERNMENTAL_ORGANISATION",
    ),
    ("NON_GOVERNMENTAL_ORGANISATION", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("ELECTION", "HAS_CONSEQUENCE", "POLITICAL_VIOLENCE"),
    ("MILITARY_ORGANISATION", "IS_COOPERATING_WITH", "GROUP_OF_INDIVIDUALS"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "NON_GOVERNMENTAL_ORGANISATION"),
    (
        "GROUP_OF_INDIVIDUALS",
        "IS_COOPERATING_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("MILITARY", "IS_PART_OF", "NON_GOVERNMENTAL_ORGANISATION"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "ELECTION"),
    ("GATHERING", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("PLACE", "HAS_CONSEQUENCE", "RIOT"),
    ("HOOLIGANISM_TROUBLEMAKING", "START_DATE", "TIME_MIN"),
    ("CIVILIAN", "INITIATED", "SUICIDE"),
    ("CIVILIAN", "IS_LOCATED_IN", "MATERIEL"),
    ("MILITARY_ORGANISATION", "IS_IN_CONTACT_WITH", "MILITARY"),
    ("FIRE", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("GATHERING", "HAS_CONSEQUENCE", "NATURAL_EVENT"),
    ("RIOT", "START_DATE", "TIME_FUZZY"),
    ("THEFT", "STARTED_IN", "CRIMINAL_ARREST"),
    ("FIRE", "STARTED_IN", "PLACE"),
    ("DRUG_OPERATION", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "FIRE"),
    ("CIVILIAN", "INITIATED", "AGITATING_TROUBLE_MAKING"),
    ("CIVILIAN", "INITIATED", "THEFT"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "TRAFFICKING"),
    ("DRUG_OPERATION", "STARTED_IN", "PLACE"),
    ("ACCIDENT", "START_DATE", "TIME_MIN"),
    ("CIVIL_WAR_OUTBREAK", "HAS_CONSEQUENCE", "COUP_D_ETAT"),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "BOMBING"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "FIRE"),
    ("TERRORIST_OR_CRIMINAL", "IS_IN_CONTACT_WITH", "MILITARY_ORGANISATION"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("TRAFFICKING", "START_DATE", "TIME_MIN"),
    ("COUP_D_ETAT", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("DEMONSTRATION", "START_DATE", "TIME_FUZZY"),
    ("RIOT", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("MILITARY", "HAS_CONTROL_OVER", "PLACE"),
    ("CIVILIAN", "IS_COOPERATING_WITH", "MILITARY_ORGANISATION"),
    ("NATURAL_EVENT", "HAS_CONSEQUENCE", "FIRE"),
    (
        "INTERGOVERNMENTAL_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("NATURAL_EVENT", "START_DATE", "TIME_MIN"),
    ("POLITICAL_VIOLENCE", "IS_LOCATED_IN", "PLACE"),
    ("TERRORIST_OR_CRIMINAL", "HAS_FAMILY_RELATIONSHIP", "MILITARY"),
    ("NATURAL_CAUSES_DEATH", "END_DATE", "TIME_EXACT"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "THEFT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_OF_SIZE", "QUANTITY_FUZZY"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_COOPERATING_WITH",
        "MILITARY_ORGANISATION",
    ),
    ("CIVILIAN", "INITIATED", "ELECTION"),
    ("STRIKE", "HAS_CONSEQUENCE", "RIOT"),
    ("CIVIL_WAR_OUTBREAK", "END_DATE", "TIME_EXACT"),
    ("THEFT", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("GATHERING", "HAS_CONSEQUENCE", "RIOT"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "POLITICAL_VIOLENCE"),
    ("MILITARY_ORGANISATION", "IS_AT_ODDS_WITH", "TERRORIST_OR_CRIMINAL"),
    ("TERRORIST_OR_CRIMINAL", "IS_COOPERATING_WITH", "TERRORIST_OR_CRIMINAL"),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "POLITICAL_VIOLENCE"),
    ("STRIKE", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("TERRORIST_OR_CRIMINAL", "GENDER_MALE", "TERRORIST_OR_CRIMINAL"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INITIATED", "GATHERING"),
    ("MILITARY", "IS_OF_NATIONALITY", "NATIONALITY"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "HAS_CONTROL_OVER",
        "TERRORIST_OR_CRIMINAL",
    ),
    ("MATERIEL", "HAS_FOR_WIDTH", "WIDTH"),
    ("POLITICAL_VIOLENCE", "START_DATE", "TIME_EXACT"),
    ("CIVIL_WAR_OUTBREAK", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("THEFT", "HAS_CONSEQUENCE", "CIVIL_WAR_OUTBREAK"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "CRIMINAL_ARREST"),
    ("AGITATING_TROUBLE_MAKING", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("STRIKE", "START_DATE", "TIME_EXACT"),
    ("RIOT", "INJURED_NUMBER", "QUANTITY_EXACT"),
    (
        "INTERGOVERNMENTAL_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    ("POLITICAL_VIOLENCE", "END_DATE", "TIME_FUZZY"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("FIRE", "HAS_CONSEQUENCE", "GATHERING"),
    ("MATERIEL", "HAS_QUANTITY", "QUANTITY_MIN"),
    ("BOMBING", "HAS_CONSEQUENCE", "THEFT"),
    ("GATHERING", "END_DATE", "TIME_MIN"),
    ("CIVIL_WAR_OUTBREAK", "DEATHS_NUMBER", "QUANTITY_MIN"),
    ("STRIKE", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "GATHERING"),
    ("ELECTION", "HAS_CONSEQUENCE", "FIRE"),
    ("NON_GOVERNMENTAL_ORGANISATION", "WAS_CREATED_IN", "TIME_EXACT"),
    ("THEFT", "END_DATE", "TIME_EXACT"),
    ("SUICIDE", "STARTED_IN", "PLACE"),
    ("MILITARY", "HAS_FAMILY_RELATIONSHIP", "MILITARY"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_AT_ODDS_WITH", "GROUP_OF_INDIVIDUALS"),
    ("GROUP_OF_INDIVIDUALS", "IS_AT_ODDS_WITH", "CIVILIAN"),
    ("POLLUTION", "STARTED_IN", "PLACE"),
    ("MILITARY", "HAS_CONTROL_OVER", "NON_GOVERNMENTAL_ORGANISATION"),
    ("PLACE", "HAS_CONTROL_OVER", "MATERIEL"),
    ("ACCIDENT", "INJURED_NUMBER", "QUANTITY_MIN"),
    ("POLLUTION", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("HOOLIGANISM_TROUBLEMAKING", "HAS_CONSEQUENCE", "THEFT"),
    ("AGITATING_TROUBLE_MAKING", "STARTED_IN", "PLACE"),
    ("CIVILIAN", "HAS_FAMILY_RELATIONSHIP", "MILITARY"),
    ("MATERIEL", "WAS_CREATED_IN", "TIME_MIN"),
    ("GROUP_OF_INDIVIDUALS", "IS_COOPERATING_WITH", "INTERGOVERNMENTAL_ORGANISATION"),
    ("AGITATING_TROUBLE_MAKING", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("EPIDEMIC", "STARTED_IN", "PLACE"),
    ("CIVIL_WAR_OUTBREAK", "HAS_CONSEQUENCE", "RIOT"),
    ("FIRE", "HAS_CONSEQUENCE", "CBRN_EVENT"),
    ("CIVILIAN", "IS_IN_CONTACT_WITH", "MILITARY_ORGANISATION"),
    ("NON_GOVERNMENTAL_ORGANISATION", "START_DATE", "TIME_FUZZY"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "POLITICAL_VIOLENCE"),
    ("POLITICAL_VIOLENCE", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("NON_GOVERNMENTAL_ORGANISATION", "WAS_DISSOLVED_IN", "TIME_FUZZY"),
    ("CIVILIAN", "RESIDES_IN", "PLACE"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "THEFT"),
    ("CIVILIAN", "IS_COOPERATING_WITH", "TERRORIST_OR_CRIMINAL"),
    ("MILITARY_ORGANISATION", "IS_COOPERATING_WITH", "CIVILIAN"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_COOPERATING_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("AGITATING_TROUBLE_MAKING", "START_DATE", "TIME_EXACT"),
    ("COUP_D_ETAT", "END_DATE", "TIME_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "BOMBING"),
    ("GATHERING", "IS_LOCATED_IN", "PLACE"),
    ("STRIKE", "IS_LOCATED_IN", "PLACE"),
    ("BOMBING", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("BOMBING", "STARTED_IN", "PLACE"),
    ("GROUP_OF_INDIVIDUALS", "CREATED", "NON_GOVERNMENTAL_ORGANISATION"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "TRAFFICKING"),
    ("CIVILIAN", "IS_AT_ODDS_WITH", "CIVILIAN"),
    ("CIVILIAN", "HAS_CONTROL_OVER", "TERRORIST_OR_CRIMINAL"),
    ("COUP_D_ETAT", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "DRUG_OPERATION"),
    ("MILITARY_ORGANISATION", "HAS_CONTROL_OVER", "PLACE"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "FIRE"),
    ("MILITARY_ORGANISATION", "IS_IN_CONTACT_WITH", "GROUP_OF_INDIVIDUALS"),
    ("ECONOMICAL_CRISIS", "IS_LOCATED_IN", "PLACE"),
    (
        "GROUP_OF_INDIVIDUALS",
        "IS_IN_CONTACT_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("MILITARY", "INITIATED", "CRIMINAL_ARREST"),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "TRAFFICKING"),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "FIRE"),
    ("SUICIDE", "HAS_CONSEQUENCE", "GATHERING"),
    ("GROUP_OF_INDIVIDUALS", "STARTED_IN", "PLACE"),
    ("GATHERING", "START_DATE", "TIME_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "POLITICAL_VIOLENCE"),
    ("CBRN_EVENT", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    (
        "TERRORIST_OR_CRIMINAL",
        "IS_AT_ODDS_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("MILITARY", "IS_IN_CONTACT_WITH", "MILITARY_ORGANISATION"),
    ("PLACE", "IS_LOCATED_IN", "PLACE"),
    ("FIRE", "END_DATE", "TIME_EXACT"),
    ("GATHERING", "END_DATE", "TIME_FUZZY"),
    ("STRIKE", "END_DATE", "TIME_FUZZY"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "EPIDEMIC"),
    ("POLITICAL_VIOLENCE", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("TRAFFICKING", "STARTED_IN", "PLACE"),
    ("EPIDEMIC", "HAS_CONSEQUENCE", "GATHERING"),
    ("MILITARY_ORGANISATION", "IS_OF_NATIONALITY", "NATIONALITY"),
    ("CBRN_EVENT", "IS_LOCATED_IN", "PLACE"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_IN_CONTACT_WITH", "TERRORIST_OR_CRIMINAL"),
    ("MILITARY", "IS_PART_OF", "GROUP_OF_INDIVIDUALS"),
    ("CIVILIAN", "IS_IN_CONTACT_WITH", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("MATERIEL", "WAS_CREATED_IN", "TIME_FUZZY"),
    ("EPIDEMIC", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "IS_IN_CONTACT_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("MILITARY", "IS_LOCATED_IN", "PLACE"),
    ("POLLUTION", "HAS_CONSEQUENCE", "CBRN_EVENT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INITIATED", "CIVIL_WAR_OUTBREAK"),
    ("BOMBING", "HAS_CONSEQUENCE", "GATHERING"),
    ("NATURAL_EVENT", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("NATURAL_CAUSES_DEATH", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_OF_SIZE", "QUANTITY_EXACT"),
    ("AGITATING_TROUBLE_MAKING", "HAS_CONSEQUENCE", "CBRN_EVENT"),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "CBRN_EVENT"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "TRAFFICKING"),
    ("TERRORIST_OR_CRIMINAL", "IS_AT_ODDS_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("STRIKE", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("GATHERING", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("CBRN_EVENT", "START_DATE", "TIME_EXACT"),
    ("CIVILIAN", "IS_AT_ODDS_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("MILITARY_ORGANISATION", "HAS_CONTROL_OVER", "NON_GOVERNMENTAL_ORGANISATION"),
    ("FIRE", "HAS_CONSEQUENCE", "CIVIL_WAR_OUTBREAK"),
    ("RIOT", "HAS_CONSEQUENCE", "POLITICAL_VIOLENCE"),
    ("CIVILIAN", "IS_COOPERATING_WITH", "INTERGOVERNMENTAL_ORGANISATION"),
    ("THEFT", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("CBRN_EVENT", "END_DATE", "TIME_FUZZY"),
    ("CIVIL_WAR_OUTBREAK", "START_DATE", "TIME_EXACT"),
    ("CIVILIAN", "IS_DEAD_ON", "TIME_FUZZY"),
    ("MILITARY", "GENDER_MALE", "MILITARY"),
    ("DRUG_OPERATION", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "POLITICAL_VIOLENCE"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_COOPERATING_WITH",
        "INTERGOVERNMENTAL_ORGANISATION",
    ),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "IS_AT_ODDS_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("BOMBING", "HAS_CONSEQUENCE", "CBRN_EVENT"),
    ("BOMBING", "HAS_CONSEQUENCE", "BOMBING"),
    ("MATERIEL", "HAS_QUANTITY", "QUANTITY_EXACT"),
    ("GATHERING", "HAS_CONSEQUENCE", "EPIDEMIC"),
    ("MILITARY_ORGANISATION", "OPERATES_IN", "PLACE"),
    ("INTERGOVERNMENTAL_ORGANISATION", "IS_COOPERATING_WITH", "CIVILIAN"),
    ("GATHERING", "START_DATE", "TIME_MAX"),
    ("DRUG_OPERATION", "END_DATE", "TIME_EXACT"),
    ("MILITARY", "IS_AT_ODDS_WITH", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("ELECTION", "STARTED_IN", "PLACE"),
    ("POLITICAL_VIOLENCE", "HAS_CONSEQUENCE", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "THEFT"),
    ("NATURAL_EVENT", "HAS_CONSEQUENCE", "GATHERING"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "START_DATE", "TIME_FUZZY"),
    ("GROUP_OF_INDIVIDUALS", "CREATED", "MATERIEL"),
    ("ACCIDENT", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "IS_IN_CONTACT_WITH", "INTERGOVERNMENTAL_ORGANISATION"),
    ("TERRORIST_OR_CRIMINAL", "GENDER_FEMALE", "TERRORIST_OR_CRIMINAL"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "FIRE"),
    ("MILITARY", "IS_IN_CONTACT_WITH", "TERRORIST_OR_CRIMINAL"),
    ("THEFT", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("TERRORIST_OR_CRIMINAL", "IS_AT_ODDS_WITH", "MILITARY"),
    ("AGITATING_TROUBLE_MAKING", "END_DATE", "TIME_EXACT"),
    ("DRUG_OPERATION", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "STRIKE"),
    ("MILITARY_ORGANISATION", "INITIATED", "CRIMINAL_ARREST"),
    ("CIVILIAN", "RESIDES_IN", "CRIMINAL_ARREST"),
    ("CIVILIAN", "IS_AT_ODDS_WITH", "MILITARY"),
    ("MILITARY_ORGANISATION", "HAS_CONTROL_OVER", "MILITARY"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "DRUG_OPERATION"),
    (
        "INTERGOVERNMENTAL_ORGANISATION",
        "IS_COOPERATING_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("STRIKE", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "CBRN_EVENT"),
    ("INTERGOVERNMENTAL_ORGANISATION", "IS_IN_CONTACT_WITH", "GROUP_OF_INDIVIDUALS"),
    ("NATURAL_CAUSES_DEATH", "IS_LOCATED_IN", "PLACE"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "HAS_CONSEQUENCE", "THEFT"),
    ("NATURAL_EVENT", "STARTED_IN", "PLACE"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "DRUG_OPERATION"),
    ("CIVIL_WAR_OUTBREAK", "IS_LOCATED_IN", "PLACE"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INJURED_NUMBER", "QUANTITY_EXACT"),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "IS_AT_ODDS_WITH",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "INTERGOVERNMENTAL_ORGANISATION",
    ),
    ("NATURAL_EVENT", "HAS_CONSEQUENCE", "CBRN_EVENT"),
    ("GROUP_OF_INDIVIDUALS", "IS_LOCATED_IN", "GATHERING"),
    ("AGITATING_TROUBLE_MAKING", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "STARTED_IN", "PLACE"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "TRAFFICKING"),
    ("RIOT", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("ECONOMICAL_CRISIS", "START_DATE", "TIME_MIN"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "FIRE"),
    ("POLLUTION", "HAS_CONSEQUENCE", "POLLUTION"),
    ("CIVILIAN", "CREATED", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("INTERGOVERNMENTAL_ORGANISATION", "INITIATED", "GATHERING"),
    ("POLITICAL_VIOLENCE", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("GROUP_OF_INDIVIDUALS", "HAS_CONTROL_OVER", "PLACE"),
    ("AGITATING_TROUBLE_MAKING", "HAS_CONSEQUENCE", "POLLUTION"),
    ("TERRORIST_OR_CRIMINAL", "HAS_FAMILY_RELATIONSHIP", "CIVILIAN"),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "POLLUTION"),
    ("CIVILIAN", "INITIATED", "TRAFFICKING"),
    ("FIRE", "HAS_CONSEQUENCE", "COUP_D_ETAT"),
    ("CIVILIAN", "IS_IN_CONTACT_WITH", "INTERGOVERNMENTAL_ORGANISATION"),
    ("CIVILIAN", "INITIATED", "FIRE"),
    ("COUP_D_ETAT", "START_DATE", "TIME_EXACT"),
    ("CIVILIAN", "RESIDES_IN", "MATERIEL"),
    ("NATURAL_CAUSES_DEATH", "START_DATE", "TIME_EXACT"),
    ("CRIMINAL_ARREST", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("AGITATING_TROUBLE_MAKING", "HAS_CONSEQUENCE", "CIVIL_WAR_OUTBREAK"),
    ("CRIMINAL_ARREST", "STARTED_IN", "PLACE"),
    ("POLLUTION", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("ELECTION", "HAS_CONSEQUENCE", "GATHERING"),
    ("RIOT", "HAS_CONSEQUENCE", "FIRE"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "AGITATING_TROUBLE_MAKING"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "THEFT"),
    ("CBRN_EVENT", "DEATHS_NUMBER", "QUANTITY_MAX"),
    ("NATURAL_CAUSES_DEATH", "END_DATE", "TIME_FUZZY"),
    ("AGITATING_TROUBLE_MAKING", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    (
        "GROUP_OF_INDIVIDUALS",
        "HAS_CONTROL_OVER",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_AT_ODDS_WITH",
        "TERRORIST_OR_CRIMINAL",
    ),
    ("EPIDEMIC", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("POLLUTION", "END_DATE", "TIME_EXACT"),
    ("MILITARY", "IS_DEAD_ON", "TIME_EXACT"),
    ("CIVIL_WAR_OUTBREAK", "END_DATE", "TIME_FUZZY"),
    ("THEFT", "IS_LOCATED_IN", "PLACE"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "FIRE"),
    ("CIVILIAN", "IS_LOCATED_IN", "GATHERING"),
    ("MATERIEL", "WEIGHS", "WEIGHT"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_COOPERATING_WITH", "MILITARY_ORGANISATION"),
    ("MILITARY_ORGANISATION", "HAS_CONTROL_OVER", "MATERIEL"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_AT_ODDS_WITH", "MILITARY"),
    ("TERRORIST_OR_CRIMINAL", "IS_DEAD_ON", "TIME_EXACT"),
    ("TERRORIST_OR_CRIMINAL", "IS_PART_OF", "MILITARY_ORGANISATION"),
    ("CIVILIAN", "IS_DEAD_ON", "TIME_EXACT"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "DRUG_OPERATION"),
    ("CIVILIAN", "IS_PART_OF", "MILITARY_ORGANISATION"),
    ("THEFT", "HAS_CONSEQUENCE", "NON_GOVERNMENTAL_ORGANISATION"),
    ("POLITICAL_VIOLENCE", "HAS_CONSEQUENCE", "RIOT"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "ELECTION"),
    ("ELECTION", "HAS_CONSEQUENCE", "CBRN_EVENT"),
    ("ELECTION", "HAS_CONSEQUENCE", "BOMBING"),
    ("MILITARY_ORGANISATION", "IS_AT_ODDS_WITH", "MILITARY_ORGANISATION"),
    ("POLITICAL_VIOLENCE", "START_DATE", "TIME_FUZZY"),
    ("EPIDEMIC", "HAS_CONSEQUENCE", "STRIKE"),
    ("GATHERING", "START_DATE", "TIME_MIN"),
    ("STRIKE", "START_DATE", "TIME_FUZZY"),
    ("COUP_D_ETAT", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("COUP_D_ETAT", "IS_LOCATED_IN", "PLACE"),
    ("MILITARY", "HAS_FAMILY_RELATIONSHIP", "CIVILIAN"),
    ("PLACE", "IS_LOCATED_IN", "MATERIEL"),
    ("MATERIEL", "IS_REGISTERED_AS", "MATERIAL_REFERENCE"),
    ("GROUP_OF_INDIVIDUALS", "IS_COOPERATING_WITH", "CIVILIAN"),
    ("STRIKE", "END_DATE", "TIME_MAX"),
    ("THEFT", "START_DATE", "TIME_EXACT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INITIATED", "ECONOMICAL_CRISIS"),
    ("GROUP_OF_INDIVIDUALS", "HAS_CONTROL_OVER", "NON_GOVERNMENTAL_ORGANISATION"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_IN_CONTACT_WITH", "MILITARY"),
    ("THEFT", "END_DATE", "TIME_FUZZY"),
    ("MATERIEL", "HAS_FOR_HEIGHT", "HEIGHT"),
    ("GROUP_OF_INDIVIDUALS", "IS_PART_OF", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("MILITARY_ORGANISATION", "IS_IN_CONTACT_WITH", "TERRORIST_OR_CRIMINAL"),
    ("CBRN_EVENT", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "CREATED", "MATERIEL"),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "GATHERING"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "CIVIL_WAR_OUTBREAK"),
    ("POLLUTION", "HAS_CONSEQUENCE", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INITIATED", "ACCIDENT"),
    ("GROUP_OF_INDIVIDUALS", "IS_IN_CONTACT_WITH", "GROUP_OF_INDIVIDUALS"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("FIRE", "HAS_CONSEQUENCE", "RIOT"),
    ("MATERIEL", "HAS_COLOR", "COLOR"),
    ("INTERGOVERNMENTAL_ORGANISATION", "IS_IN_CONTACT_WITH", "CIVILIAN"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "THEFT"),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("EPIDEMIC", "HAS_CONSEQUENCE", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "BOMBING"),
    ("TRAFFICKING", "END_DATE", "TIME_EXACT"),
    ("TERRORIST_OR_CRIMINAL", "IS_AT_ODDS_WITH", "GROUP_OF_INDIVIDUALS"),
    ("COUP_D_ETAT", "END_DATE", "TIME_FUZZY"),
    ("AGITATING_TROUBLE_MAKING", "START_DATE", "TIME_FUZZY"),
    ("ELECTION", "END_DATE", "TIME_EXACT"),
    ("FIRE", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("CIVILIAN", "IS_AT_ODDS_WITH", "GROUP_OF_INDIVIDUALS"),
    ("MILITARY_ORGANISATION", "HAS_CONTROL_OVER", "GROUP_OF_INDIVIDUALS"),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "IS_COOPERATING_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("DRUG_OPERATION", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "STRIKE"),
    ("THEFT", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("NATURAL_CAUSES_DEATH", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("NATURAL_EVENT", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_OF_SIZE", "QUANTITY_FUZZY"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "ACCIDENT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "HAS_CONTROL_OVER", "CIVILIAN"),
    ("GROUP_OF_INDIVIDUALS", "HAS_CONTROL_OVER", "MILITARY"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "INITIATED",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "HAS_CONTROL_OVER", "PLACE"),
    ("CIVIL_WAR_OUTBREAK", "START_DATE", "TIME_MIN"),
    ("NON_GOVERNMENTAL_ORGANISATION", "WAS_DISSOLVED_IN", "TIME_MIN"),
    ("EPIDEMIC", "END_DATE", "TIME_EXACT"),
    ("MILITARY", "HAS_CONTROL_OVER", "MILITARY_ORGANISATION"),
    (
        "TERRORIST_OR_CRIMINAL",
        "IS_COOPERATING_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("POLLUTION", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "GATHERING"),
    ("GROUP_OF_INDIVIDUALS", "IS_COOPERATING_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("TERRORIST_OR_CRIMINAL", "RESIDES_IN", "PLACE"),
    ("CIVILIAN", "HAS_CONTROL_OVER", "MILITARY_ORGANISATION"),
    ("NON_GOVERNMENTAL_ORGANISATION", "HAS_CONTROL_OVER", "TERRORIST_OR_CRIMINAL"),
    ("GATHERING", "START_DATE", "TIME_FUZZY"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "END_DATE", "TIME_EXACT"),
    ("EPIDEMIC", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "HAS_CONTROL_OVER",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("ACCIDENT", "STARTED_IN", "MATERIEL"),
    ("MATERIEL", "HAS_QUANTITY", "QUANTITY_FUZZY"),
    ("ELECTION", "HAS_CONSEQUENCE", "CIVIL_WAR_OUTBREAK"),
    ("FIRE", "END_DATE", "TIME_FUZZY"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_OF_NATIONALITY", "NATIONALITY"),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "NATURAL_EVENT"),
    ("CRIMINAL_ARREST", "STARTED_IN", "CRIMINAL_ARREST"),
    ("GATHERING", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("GATHERING", "HAS_CONSEQUENCE", "THEFT"),
    ("STRIKE", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("FIRE", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "OPERATES_IN", "PLACE"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "COUP_D_ETAT"),
    ("THEFT", "HAS_CONSEQUENCE", "HOOLIGANISM_TROUBLEMAKING"),
    ("TERRORIST_OR_CRIMINAL", "IS_IN_CONTACT_WITH", "CIVILIAN"),
    ("INTERGOVERNMENTAL_ORGANISATION", "IS_AT_ODDS_WITH", "MILITARY_ORGANISATION"),
    ("ACCIDENT", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("RIOT", "STARTED_IN", "PLACE"),
    ("THEFT", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "BOMBING"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_AT_ODDS_WITH", "GROUP_OF_INDIVIDUALS"),
    ("RIOT", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("CIVILIAN", "HAS_FAMILY_RELATIONSHIP", "TERRORIST_OR_CRIMINAL"),
    ("FIRE", "IS_LOCATED_IN", "PLACE"),
    ("THEFT", "IS_LOCATED_IN", "CRIMINAL_ARREST"),
    ("DRUG_OPERATION", "IS_LOCATED_IN", "PLACE"),
    ("GROUP_OF_INDIVIDUALS", "HAS_CONTROL_OVER", "MATERIEL"),
    ("EPIDEMIC", "HAS_CONSEQUENCE", "ECONOMICAL_CRISIS"),
    ("GROUP_OF_INDIVIDUALS", "IS_PART_OF", "INTERGOVERNMENTAL_ORGANISATION"),
    ("ACCIDENT", "END_DATE", "TIME_EXACT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_COOPERATING_WITH", "CIVILIAN"),
    ("GATHERING", "HAS_CONSEQUENCE", "ELECTION"),
    ("GROUP_OF_INDIVIDUALS", "IS_COOPERATING_WITH", "MILITARY"),
    ("MILITARY", "IS_COOPERATING_WITH", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("AGITATING_TROUBLE_MAKING", "HAS_CONSEQUENCE", "RIOT"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("SUICIDE", "HAS_CONSEQUENCE", "ACCIDENT"),
    (
        "TERRORIST_OR_CRIMINAL",
        "IS_IN_CONTACT_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "HAS_CONTROL_OVER",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    ("TERRORIST_OR_CRIMINAL", "IS_BORN_ON", "TIME_EXACT"),
    ("CBRN_EVENT", "START_DATE", "TIME_FUZZY"),
    ("GROUP_OF_INDIVIDUALS", "IS_AT_ODDS_WITH", "MILITARY_ORGANISATION"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_PART_OF",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("CIVILIAN", "IS_COOPERATING_WITH", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("INTERGOVERNMENTAL_ORGANISATION", "IS_COOPERATING_WITH", "GROUP_OF_INDIVIDUALS"),
    ("GATHERING", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("CIVIL_WAR_OUTBREAK", "START_DATE", "TIME_FUZZY"),
    ("FIRE", "START_DATE", "TIME_EXACT"),
    ("BOMBING", "HAS_CONSEQUENCE", "ECONOMICAL_CRISIS"),
    ("TRAFFICKING", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "GROUP_OF_INDIVIDUALS",
    ),
    ("GROUP_OF_INDIVIDUALS", "IS_IN_CONTACT_WITH", "CIVILIAN"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "GATHERING"),
    ("DRUG_OPERATION", "START_DATE", "TIME_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "CBRN_EVENT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "OPERATES_IN", "PLACE"),
    ("CIVIL_WAR_OUTBREAK", "END_DATE", "TIME_MAX"),
    ("MILITARY", "HAS_CONTROL_OVER", "TERRORIST_OR_CRIMINAL"),
    ("CIVILIAN", "HAS_CONTROL_OVER", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("DRUG_OPERATION", "END_DATE", "TIME_FUZZY"),
    ("CIVILIAN", "INITIATED", "GATHERING"),
    ("TERRORIST_OR_CRIMINAL", "IS_AT_ODDS_WITH", "CIVILIAN"),
    ("ACCIDENT", "DEATHS_NUMBER", "QUANTITY_MIN"),
    ("CIVILIAN", "IS_PART_OF", "INTERGOVERNMENTAL_ORGANISATION"),
    ("NATURAL_EVENT", "HAS_CONSEQUENCE", "NATURAL_EVENT"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("CIVILIAN", "IS_DEAD_ON", "TIME_MIN"),
    ("SUICIDE", "END_DATE", "TIME_FUZZY"),
    ("CRIMINAL_ARREST", "END_DATE", "TIME_EXACT"),
    ("RIOT", "HAS_CONSEQUENCE", "GATHERING"),
    ("MILITARY_ORGANISATION", "IS_AT_ODDS_WITH", "INTERGOVERNMENTAL_ORGANISATION"),
    ("SUICIDE", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("TERRORIST_OR_CRIMINAL", "IS_IN_CONTACT_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "HAS_CONTROL_OVER",
        "INTERGOVERNMENTAL_ORGANISATION",
    ),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INITIATED", "CRIMINAL_ARREST"),
    ("THEFT", "HAS_CONSEQUENCE", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "HAS_CONTROL_OVER", "MILITARY"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "ECONOMICAL_CRISIS"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "BOMBING"),
    ("AGITATING_TROUBLE_MAKING", "END_DATE", "TIME_FUZZY"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_PART_OF",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    ("CIVILIAN", "IS_COOPERATING_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("HOOLIGANISM_TROUBLEMAKING", "STARTED_IN", "PLACE"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "GATHERING"),
    ("SUICIDE", "IS_LOCATED_IN", "PLACE"),
    ("POLITICAL_VIOLENCE", "HAS_CONSEQUENCE", "POLITICAL_VIOLENCE"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "HAS_CONSEQUENCE", "FIRE"),
    ("NON_GOVERNMENTAL_ORGANISATION", "OPERATES_IN", "GATHERING"),
    ("CIVILIAN", "IS_IN_CONTACT_WITH", "CIVILIAN"),
    ("CRIMINAL_ARREST", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("POLLUTION", "IS_LOCATED_IN", "PLACE"),
    ("CIVILIAN", "INITIATED", "CBRN_EVENT"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_COOPERATING_WITH",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    ("GROUP_OF_INDIVIDUALS", "HAS_CONTROL_OVER", "GROUP_OF_INDIVIDUALS"),
    ("FIRE", "HAS_CONSEQUENCE", "NATURAL_CAUSES_DEATH"),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("FIRE", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("CIVILIAN", "IS_IN_CONTACT_WITH", "PLACE"),
    ("CIVILIAN", "IS_BORN_ON", "TIME_EXACT"),
    ("TERRORIST_OR_CRIMINAL", "HAS_CATEGORY", "CATEGORY_0"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("DRUG_OPERATION", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("AGITATING_TROUBLE_MAKING", "IS_LOCATED_IN", "PLACE"),
    ("GROUP_OF_INDIVIDUALS", "START_DATE", "TIME_EXACT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INITIATED", "EPIDEMIC"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("DEMONSTRATION", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("TERRORIST_OR_CRIMINAL", "CREATED", "NON_GOVERNMENTAL_ORGANISATION"),
    ("EPIDEMIC", "IS_LOCATED_IN", "PLACE"),
    ("DEMONSTRATION", "STARTED_IN", "PLACE"),
    ("NON_GOVERNMENTAL_ORGANISATION", "STARTED_IN", "PLACE"),
    ("GATHERING", "HAS_CONSEQUENCE", "GATHERING"),
    ("NATURAL_EVENT", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("BOMBING", "END_DATE", "TIME_FUZZY"),
    ("BOMBING", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "CBRN_EVENT"),
    ("MILITARY", "INITIATED", "POLITICAL_VIOLENCE"),
    ("MILITARY", "RESIDES_IN", "PLACE"),
    ("COUP_D_ETAT", "START_DATE", "TIME_FUZZY"),
    ("SUICIDE", "START_DATE", "TIME_EXACT"),
    ("NATURAL_CAUSES_DEATH", "START_DATE", "TIME_FUZZY"),
    ("GROUP_OF_INDIVIDUALS", "IS_AT_ODDS_WITH", "TERRORIST_OR_CRIMINAL"),
    ("TERRORIST_OR_CRIMINAL", "IS_IN_CONTACT_WITH", "MILITARY"),
    ("RIOT", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "CREATED",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("POLLUTION", "START_DATE", "TIME_EXACT"),
    ("FIRE", "HAS_CONSEQUENCE", "POLLUTION"),
    ("BOMBING", "IS_LOCATED_IN", "PLACE"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_AT_ODDS_WITH", "CIVILIAN"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INITIATED", "DEMONSTRATION"),
    ("PLACE", "HAS_LATITUDE", "LATITUDE"),
    ("CIVILIAN", "IS_COOPERATING_WITH", "MILITARY"),
    ("COUP_D_ETAT", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "FIRE"),
    ("POLLUTION", "END_DATE", "TIME_FUZZY"),
    ("EPIDEMIC", "START_DATE", "TIME_EXACT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "HAS_CONTROL_OVER", "MATERIEL"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "POLLUTION"),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    ("MILITARY", "IS_AT_ODDS_WITH", "CIVILIAN"),
    ("GATHERING", "HAS_CONSEQUENCE", "BOMBING"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_COOPERATING_WITH", "MILITARY"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "STRIKE"),
    ("DRUG_OPERATION", "HAS_CONSEQUENCE", "CIVIL_WAR_OUTBREAK"),
    ("GROUP_OF_INDIVIDUALS", "IS_PART_OF", "GROUP_OF_INDIVIDUALS"),
    ("MATERIEL", "HAS_CONTROL_OVER", "CIVILIAN"),
    ("RIOT", "STARTED_IN", "CRIMINAL_ARREST"),
    ("HOOLIGANISM_TROUBLEMAKING", "IS_LOCATED_IN", "PLACE"),
    ("GROUP_OF_INDIVIDUALS", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "CIVIL_WAR_OUTBREAK"),
    ("GROUP_OF_INDIVIDUALS", "IS_LOCATED_IN", "PLACE"),
    ("NATURAL_CAUSES_DEATH", "END_DATE", "TIME_MIN"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "HOOLIGANISM_TROUBLEMAKING"),
    ("EPIDEMIC", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "IS_COOPERATING_WITH", "GROUP_OF_INDIVIDUALS"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "DEMONSTRATION"),
    ("NATURAL_EVENT", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("CIVILIAN", "IS_IN_CONTACT_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("BOMBING", "START_DATE", "TIME_EXACT"),
    ("CIVILIAN", "HAS_CATEGORY", "CATEGORY_0"),
    ("GATHERING", "IS_LOCATED_IN", "GATHERING"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_IN_CONTACT_WITH", "CIVILIAN"),
    ("CIVILIAN", "IS_AT_ODDS_WITH", "TERRORIST_OR_CRIMINAL"),
    ("TRAFFICKING", "IS_LOCATED_IN", "PLACE"),
    ("GROUP_OF_INDIVIDUALS", "IS_IN_CONTACT_WITH", "MILITARY"),
    ("MILITARY", "IS_IN_CONTACT_WITH", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("ELECTION", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("SUICIDE", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("THEFT", "HAS_CONSEQUENCE", "RIOT"),
    ("SUICIDE", "END_DATE", "TIME_EXACT"),
    ("FIRE", "END_DATE", "TIME_MAX"),
    ("THEFT", "START_DATE", "TIME_FUZZY"),
    ("POLLUTION", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("GATHERING", "HAS_CONSEQUENCE", "POLITICAL_VIOLENCE"),
    ("ACCIDENT", "STARTED_IN", "PLACE"),
    ("POLITICAL_VIOLENCE", "HAS_CONSEQUENCE", "FIRE"),
    ("POLITICAL_VIOLENCE", "START_DATE", "TIME_MIN"),
    ("AGITATING_TROUBLE_MAKING", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("INTERGOVERNMENTAL_ORGANISATION", "HAS_CONTROL_OVER", "PLACE"),
    ("THEFT", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("THEFT", "HAS_CONSEQUENCE", "THEFT"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_IN_CONTACT_WITH", "MILITARY"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "OPERATES_IN", "CRIMINAL_ARREST"),
    ("MILITARY_ORGANISATION", "INITIATED", "BOMBING"),
    ("CIVILIAN", "INITIATED", "CIVIL_WAR_OUTBREAK"),
    ("ACCIDENT", "START_DATE", "TIME_EXACT"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "INITIATED",
        "ILLEGAL_CIVIL_DEMONSTRATION",
    ),
    ("FIRE", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("TRAFFICKING", "START_DATE", "TIME_EXACT"),
    ("POLLUTION", "HAS_CONSEQUENCE", "EPIDEMIC"),
    ("RIOT", "HAS_CONSEQUENCE", "CIVIL_WAR_OUTBREAK"),
    ("POLLUTION", "START_DATE", "TIME_MAX"),
    ("NATURAL_EVENT", "START_DATE", "TIME_EXACT"),
    ("MILITARY", "IS_AT_ODDS_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("CIVILIAN", "IS_IN_CONTACT_WITH", "MILITARY"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "HAS_CONTROL_OVER",
        "GROUP_OF_INDIVIDUALS",
    ),
    ("BOMBING", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("GROUP_OF_INDIVIDUALS", "HAS_CONTROL_OVER", "CIVILIAN"),
    ("TERRORIST_OR_CRIMINAL", "CREATED", "MATERIEL"),
    ("BOMBING", "END_DATE", "TIME_EXACT"),
    ("MILITARY", "IS_IN_CONTACT_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "EPIDEMIC"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "STRIKE"),
    ("ACCIDENT", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("ELECTION", "END_DATE", "TIME_FUZZY"),
    ("RIOT", "IS_LOCATED_IN", "CRIMINAL_ARREST"),
    ("GROUP_OF_INDIVIDUALS", "IS_AT_ODDS_WITH", "INTERGOVERNMENTAL_ORGANISATION"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "CIVIL_WAR_OUTBREAK"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "ACCIDENT"),
    ("RIOT", "END_DATE", "TIME_EXACT"),
    ("CIVILIAN", "INITIATED", "STRIKE"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "COUP_D_ETAT"),
    ("MILITARY_ORGANISATION", "INITIATED", "POLITICAL_VIOLENCE"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "OPERATES_IN", "MATERIEL"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_AT_ODDS_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("EPIDEMIC", "END_DATE", "TIME_FUZZY"),
    ("HOOLIGANISM_TROUBLEMAKING", "END_DATE", "TIME_EXACT"),
    ("ELECTION", "IS_LOCATED_IN", "PLACE"),
    ("GROUP_OF_INDIVIDUALS", "END_DATE", "TIME_EXACT"),
    ("RIOT", "INITIATED", "ECONOMICAL_CRISIS"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "STARTED_IN", "PLACE"),
    ("RIOT", "HAS_CONSEQUENCE", "STRIKE"),
    ("NATURAL_EVENT", "END_DATE", "TIME_FUZZY"),
    ("MILITARY", "IS_PART_OF", "MILITARY_ORGANISATION"),
    ("BOMBING", "HAS_CONSEQUENCE", "POLLUTION"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "NATURAL_CAUSES_DEATH"),
    ("ACCIDENT", "IS_LOCATED_IN", "PLACE"),
    ("GROUP_OF_INDIVIDUALS", "IS_OF_NATIONALITY", "NATIONALITY"),
    ("GATHERING", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("COUP_D_ETAT", "HAS_CONSEQUENCE", "GATHERING"),
    ("STRIKE", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "STRIKE"),
    (
        "INTERGOVERNMENTAL_ORGANISATION",
        "HAS_CONTROL_OVER",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    ("TERRORIST_OR_CRIMINAL", "HAS_CONTROL_OVER", "PLACE"),
    ("CIVILIAN", "CREATED", "NON_GOVERNMENTAL_ORGANISATION"),
    ("GROUP_OF_INDIVIDUALS", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("TERRORIST_OR_CRIMINAL", "IS_IN_CONTACT_WITH", "GROUP_OF_INDIVIDUALS"),
    ("NON_GOVERNMENTAL_ORGANISATION", "END_DATE", "TIME_EXACT"),
    ("NATURAL_EVENT", "HAS_CONSEQUENCE", "NATURAL_CAUSES_DEATH"),
    ("NATURAL_EVENT", "IS_LOCATED_IN", "PLACE"),
    ("CRIMINAL_ARREST", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_PART_OF", "GROUP_OF_INDIVIDUALS"),
    ("CIVILIAN", "IS_COOPERATING_WITH", "GROUP_OF_INDIVIDUALS"),
    ("COUP_D_ETAT", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("BOMBING", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_OF_NATIONALITY", "NATIONALITY"),
    ("ELECTION", "START_DATE", "TIME_EXACT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_LOCATED_IN", "PLACE"),
    ("GATHERING", "HAS_CONSEQUENCE", "FIRE"),
    ("STRIKE", "HAS_CONSEQUENCE", "FIRE"),
    ("CIVILIAN", "INITIATED", "COUP_D_ETAT"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "EPIDEMIC"),
    ("INTERGOVERNMENTAL_ORGANISATION", "OPERATES_IN", "PLACE"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_COOPERATING_WITH",
        "GROUP_OF_INDIVIDUALS",
    ),
    (
        "TERRORIST_OR_CRIMINAL",
        "HAS_CONTROL_OVER",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("POLITICAL_VIOLENCE", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("POLITICAL_VIOLENCE", "HAS_CONSEQUENCE", "THEFT"),
    ("COUP_D_ETAT", "HAS_CONSEQUENCE", "BOMBING"),
    (
        "MILITARY_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("NON_GOVERNMENTAL_ORGANISATION", "CREATED", "MATERIEL"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "POLLUTION"),
    ("FIRE", "END_DATE", "TIME_MIN"),
    ("HOOLIGANISM_TROUBLEMAKING", "HAS_CONSEQUENCE", "HOOLIGANISM_TROUBLEMAKING"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "POLLUTION"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "ACCIDENT"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INITIATED", "RIOT"),
    ("GROUP_OF_INDIVIDUALS", "IS_LOCATED_IN", "CRIMINAL_ARREST"),
    ("ACCIDENT", "END_DATE", "TIME_FUZZY"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "COUP_D_ETAT"),
    ("CRIMINAL_ARREST", "IS_LOCATED_IN", "PLACE"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_COOPERATING_WITH", "CIVILIAN"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("RIOT", "END_DATE", "TIME_MAX"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INITIATED", "AGITATING_TROUBLE_MAKING"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "WAS_DISSOLVED_IN", "TIME_EXACT"),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "IS_PART_OF",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("NATURAL_EVENT", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("MILITARY_ORGANISATION", "IS_AT_ODDS_WITH", "CIVILIAN"),
    ("FIRE", "START_DATE", "TIME_FUZZY"),
    ("COUP_D_ETAT", "HAS_CONSEQUENCE", "POLITICAL_VIOLENCE"),
    ("TERRORIST_OR_CRIMINAL", "IS_COOPERATING_WITH", "CIVILIAN"),
    ("TERRORIST_OR_CRIMINAL", "HAS_FAMILY_RELATIONSHIP", "TERRORIST_OR_CRIMINAL"),
    ("FIRE", "HAS_CONSEQUENCE", "SUICIDE"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "RIOT"),
    ("BOMBING", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("ELECTION", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("INTERGOVERNMENTAL_ORGANISATION", "IS_IN_CONTACT_WITH", "MILITARY_ORGANISATION"),
    ("NON_GOVERNMENTAL_ORGANISATION", "HAS_CONTROL_OVER", "PLACE"),
    ("DEMONSTRATION", "END_DATE", "TIME_EXACT"),
    ("MILITARY", "IS_PART_OF", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("CBRN_EVENT", "START_DATE", "TIME_MIN"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_IN_CONTACT_WITH", "GROUP_OF_INDIVIDUALS"),
    ("TERRORIST_OR_CRIMINAL", "HAS_CONTROL_OVER", "NON_GOVERNMENTAL_ORGANISATION"),
    ("EPIDEMIC", "START_DATE", "TIME_MIN"),
    ("DRUG_OPERATION", "START_DATE", "TIME_FUZZY"),
    ("INTERGOVERNMENTAL_ORGANISATION", "INITIATED", "EPIDEMIC"),
    ("POLITICAL_VIOLENCE", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("RIOT", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("FIRE", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("CRIMINAL_ARREST", "START_DATE", "TIME_EXACT"),
    ("POLITICAL_VIOLENCE", "STARTED_IN", "PLACE"),
    ("TERRORIST_OR_CRIMINAL", "IS_PART_OF", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("GROUP_OF_INDIVIDUALS", "IS_LOCATED_IN", "MATERIEL"),
    ("INTERGOVERNMENTAL_ORGANISATION", "IS_AT_ODDS_WITH", "TERRORIST_OR_CRIMINAL"),
    ("CIVILIAN", "IS_PART_OF", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("INTERGOVERNMENTAL_ORGANISATION", "INITIATED", "POLLUTION"),
    ("CIVIL_WAR_OUTBREAK", "HAS_CONSEQUENCE", "FIRE"),
    ("THEFT", "HAS_CONSEQUENCE", "BOMBING"),
    ("GROUP_OF_INDIVIDUALS", "IS_PART_OF", "NON_GOVERNMENTAL_ORGANISATION"),
    ("HOOLIGANISM_TROUBLEMAKING", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("CRIMINAL_ARREST", "END_DATE", "TIME_FUZZY"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "ECONOMICAL_CRISIS"),
    ("PLACE", "IS_IN_CONTACT_WITH", "CIVILIAN"),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "HAS_CONTROL_OVER",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("CIVILIAN", "IS_IN_CONTACT_WITH", "GROUP_OF_INDIVIDUALS"),
    ("NATURAL_EVENT", "END_DATE", "TIME_EXACT"),
    ("RIOT", "DEATHS_NUMBER", "QUANTITY_MIN"),
    ("MILITARY", "CREATED", "MATERIEL"),
    ("CIVILIAN", "IS_OF_NATIONALITY", "NATIONALITY"),
    ("THEFT", "START_DATE", "TIME_MAX"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_PART_OF", "NON_GOVERNMENTAL_ORGANISATION"),
    ("CIVILIAN", "INITIATED", "RIOT"),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("INTERGOVERNMENTAL_ORGANISATION", "HAS_CONTROL_OVER", "MATERIEL"),
    ("NATURAL_EVENT", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("CIVILIAN", "CREATED", "MATERIEL"),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "IS_COOPERATING_WITH",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    ("RIOT", "HAS_CONSEQUENCE", "RIOT"),
    ("THEFT", "HAS_CONSEQUENCE", "POLITICAL_VIOLENCE"),
    ("MILITARY", "IS_COOPERATING_WITH", "CIVILIAN"),
    ("ELECTION", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("MILITARY", "HAS_FAMILY_RELATIONSHIP", "TERRORIST_OR_CRIMINAL"),
    ("CIVILIAN", "INITIATED", "ACCIDENT"),
    ("MATERIEL", "IS_LOCATED_IN", "PLACE"),
    ("TERRORIST_OR_CRIMINAL", "IS_PART_OF", "NON_GOVERNMENTAL_ORGANISATION"),
    ("GROUP_OF_INDIVIDUALS", "IS_COOPERATING_WITH", "TERRORIST_OR_CRIMINAL"),
    ("RIOT", "OPERATES_IN", "PLACE"),
    ("CIVILIAN", "IS_PART_OF", "NON_GOVERNMENTAL_ORGANISATION"),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "CBRN_EVENT"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "RIOT"),
    ("CIVILIAN", "IS_COOPERATING_WITH", "CIVILIAN"),
    ("MILITARY_ORGANISATION", "IS_IN_CONTACT_WITH", "INTERGOVERNMENTAL_ORGANISATION"),
    ("MILITARY_ORGANISATION", "IS_AT_ODDS_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    (
        "NON_GOVERNMENTAL_ORGANISATION",
        "HAS_CONTROL_OVER",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    ("SUICIDE", "START_DATE", "TIME_FUZZY"),
    ("MILITARY", "IS_AT_ODDS_WITH", "GROUP_OF_INDIVIDUALS"),
    ("CIVIL_WAR_OUTBREAK", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("POLLUTION", "START_DATE", "TIME_FUZZY"),
    ("MILITARY", "IS_IN_CONTACT_WITH", "GROUP_OF_INDIVIDUALS"),
    ("ELECTION", "END_DATE", "TIME_MAX"),
    ("CIVILIAN", "HAS_CONTROL_OVER", "CIVILIAN"),
    ("GATHERING", "HAS_CONSEQUENCE", "ECONOMICAL_CRISIS"),
    ("CIVILIAN", "HAS_CONTROL_OVER", "PLACE"),
    ("EPIDEMIC", "START_DATE", "TIME_FUZZY"),
    ("COUP_D_ETAT", "HAS_CONSEQUENCE", "FIRE"),
    ("NON_GOVERNMENTAL_ORGANISATION", "OPERATES_IN", "PLACE"),
    ("NATURAL_CAUSES_DEATH", "START_DATE", "TIME_MIN"),
    ("EPIDEMIC", "END_DATE", "TIME_MAX"),
    ("ACCIDENT", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "CIVIL_WAR_OUTBREAK"),
    ("AGITATING_TROUBLE_MAKING", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("MILITARY", "HAS_CONTROL_OVER", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "HOOLIGANISM_TROUBLEMAKING"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_COOPERATING_WITH", "MILITARY"),
    ("MILITARY_ORGANISATION", "IS_PART_OF", "MILITARY_ORGANISATION"),
    ("GATHERING", "STARTED_IN", "PLACE"),
    ("STRIKE", "STARTED_IN", "PLACE"),
    ("EPIDEMIC", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("GATHERING", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("MILITARY", "INITIATED", "GATHERING"),
    ("PLACE", "HAS_LONGITUDE", "LONGITUDE"),
    ("EPIDEMIC", "HAS_CONSEQUENCE", "THEFT"),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "DEMONSTRATION"),
    ("ACCIDENT", "IS_LOCATED_IN", "MATERIEL"),
    ("MILITARY", "IS_PART_OF", "INTERGOVERNMENTAL_ORGANISATION"),
    ("NATURAL_EVENT", "END_DATE", "TIME_MAX"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_OF_SIZE", "QUANTITY_MIN"),
    ("GROUP_OF_INDIVIDUALS", "IS_IN_CONTACT_WITH", "MILITARY_ORGANISATION"),
    ("TERRORIST_OR_CRIMINAL", "HAS_CONTROL_OVER", "MATERIEL"),
    ("BOMBING", "START_DATE", "TIME_FUZZY"),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("CRIMINAL_ARREST", "IS_LOCATED_IN", "CRIMINAL_ARREST"),
    ("INTERGOVERNMENTAL_ORGANISATION", "HAS_CONTROL_OVER", "GROUP_OF_INDIVIDUALS"),
    ("ELECTION", "HAS_CONSEQUENCE", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_IN_CONTACT_WITH", "CIVILIAN"),
    ("ECONOMICAL_CRISIS", "STARTED_IN", "PLACE"),
    ("MILITARY", "IS_COOPERATING_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("TERRORIST_OR_CRIMINAL", "IS_AT_ODDS_WITH", "MILITARY_ORGANISATION"),
    ("RIOT", "IS_LOCATED_IN", "PLACE"),
    ("CIVILIAN", "IS_AT_ODDS_WITH", "MILITARY_ORGANISATION"),
    ("HOOLIGANISM_TROUBLEMAKING", "START_DATE", "TIME_FUZZY"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "END_DATE", "TIME_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "IS_OF_SIZE", "QUANTITY_EXACT"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "RIOT"),
    ("ECONOMICAL_CRISIS", "START_DATE", "TIME_EXACT"),
    ("MATERIEL", "HAS_FOR_LENGTH", "LENGTH"),
    ("THEFT", "HAS_CONSEQUENCE", "TRAFFICKING"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "RIOT"),
    ("PLACE", "STARTED_IN", "PLACE"),
    ("THEFT", "HAS_CONSEQUENCE", "FIRE"),
    ("THEFT", "START_DATE", "TIME_MIN"),
    ("AGITATING_TROUBLE_MAKING", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("ACCIDENT", "START_DATE", "TIME_FUZZY"),
    ("CIVIL_WAR_OUTBREAK", "HAS_CONSEQUENCE", "ECONOMICAL_CRISIS"),
    ("CBRN_EVENT", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "POLLUTION"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "WAS_CREATED_IN", "TIME_EXACT"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "SUICIDE"),
    ("TRAFFICKING", "START_DATE", "TIME_FUZZY"),
    ("CBRN_EVENT", "STARTED_IN", "PLACE"),
    ("CIVILIAN", "HAS_CONTROL_OVER", "NON_GOVERNMENTAL_ORGANISATION"),
    ("TERRORIST_OR_CRIMINAL", "IS_IN_CONTACT_WITH", "TERRORIST_OR_CRIMINAL"),
    ("CIVILIAN", "GENDER_MALE", "CIVILIAN"),
    ("NATURAL_EVENT", "START_DATE", "TIME_FUZZY"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "CRIMINAL_ARREST"),
    ("ACCIDENT", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("RIOT", "START_DATE", "TIME_EXACT"),
    ("STRIKE", "HAS_CONSEQUENCE", "GATHERING"),
    ("TRAFFICKING", "HAS_CONSEQUENCE", "THEFT"),
    ("CIVIL_WAR_OUTBREAK", "HAS_CONSEQUENCE", "ACCIDENT"),
    ("GROUP_OF_INDIVIDUALS", "IS_AT_ODDS_WITH", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "START_DATE", "TIME_FUZZY"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "DEMONSTRATION"),
    ("RIOT", "END_DATE", "TIME_FUZZY"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "INITIATED", "POLITICAL_VIOLENCE"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "COUP_D_ETAT"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_COOPERATING_WITH",
        "TERRORIST_OR_CRIMINAL",
    ),
    ("DEMONSTRATION", "START_DATE", "TIME_EXACT"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("NATURAL_EVENT", "HAS_CONSEQUENCE", "THEFT"),
    ("MILITARY_ORGANISATION", "IS_PART_OF", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("NON_GOVERNMENTAL_ORGANISATION", "HAS_CONTROL_OVER", "MATERIEL"),
    ("TERRORIST_OR_CRIMINAL", "IS_LOCATED_IN", "PLACE"),
    ("HOOLIGANISM_TROUBLEMAKING", "END_DATE", "TIME_FUZZY"),
    ("TERRORIST_OR_CRIMINAL", "HAS_CONTROL_OVER", "GROUP_OF_INDIVIDUALS"),
    (
        "MILITARY_ORGANISATION",
        "IS_COOPERATING_WITH",
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
    ),
    ("DEMONSTRATION", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("FIRE", "HAS_CONSEQUENCE", "POLITICAL_VIOLENCE"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_AT_ODDS_WITH", "MILITARY_ORGANISATION"),
    ("GATHERING", "HAS_CONSEQUENCE", "CBRN_EVENT"),
    ("MILITARY", "IS_IN_CONTACT_WITH", "CIVILIAN"),
    ("GROUP_OF_INDIVIDUALS", "IS_IN_CONTACT_WITH", "TERRORIST_OR_CRIMINAL"),
    ("CIVILIAN", "INITIATED", "CRIMINAL_ARREST"),
    ("POLLUTION", "HAS_CONSEQUENCE", "GATHERING"),
    ("NON_GOVERNMENTAL_ORGANISATION", "END_DATE", "TIME_FUZZY"),
    ("CIVILIAN", "IS_AT_ODDS_WITH", "NON_MILITARY_GOVERNMENT_ORGANISATION"),
    ("NATURAL_EVENT", "END_DATE", "TIME_MIN"),
    ("POLITICAL_VIOLENCE", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("GROUP_OF_INDIVIDUALS", "IS_AT_ODDS_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("RIOT", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("AGITATING_TROUBLE_MAKING", "HAS_CONSEQUENCE", "GATHERING"),
    ("ELECTION", "HAS_CONSEQUENCE", "RIOT"),
    ("CBRN_EVENT", "HAS_CONSEQUENCE", "GATHERING"),
    ("MILITARY_ORGANISATION", "INITIATED", "GATHERING"),
    ("TERRORIST_OR_CRIMINAL", "IS_AT_ODDS_WITH", "TERRORIST_OR_CRIMINAL"),
    ("GATHERING", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("ELECTION", "START_DATE", "TIME_FUZZY"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "OPERATES_IN", "GATHERING"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_PART_OF", "GROUP_OF_INDIVIDUALS"),
    ("MILITARY", "IS_BORN_ON", "TIME_EXACT"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("DEMONSTRATION", "IS_LOCATED_IN", "PLACE"),
    ("POLITICAL_VIOLENCE", "END_DATE", "TIME_EXACT"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_LOCATED_IN", "PLACE"),
    ("CIVILIAN", "INITIATED", "EPIDEMIC"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "MILITARY_ORGANISATION",
    ),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_COOPERATING_WITH", "GROUP_OF_INDIVIDUALS"),
    ("ELECTION", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("ECONOMICAL_CRISIS", "END_DATE", "TIME_FUZZY"),
    ("MILITARY_ORGANISATION", "IS_COOPERATING_WITH", "NON_GOVERNMENTAL_ORGANISATION"),
    ("TERRORIST_OR_CRIMINAL", "IS_BORN_IN", "PLACE"),
    ("CIVILIAN", "INITIATED", "POLLUTION"),
    ("HOOLIGANISM_TROUBLEMAKING", "START_DATE", "TIME_EXACT"),
    ("MILITARY", "INITIATED", "CIVIL_WAR_OUTBREAK"),
    ("TERRORIST_OR_CRIMINAL", "IS_PART_OF", "GROUP_OF_INDIVIDUALS"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("NATURAL_CAUSES_DEATH", "STARTED_IN", "PLACE"),
    ("NON_GOVERNMENTAL_ORGANISATION", "INITIATED", "COUP_D_ETAT"),
    ("CIVILIAN", "IS_PART_OF", "GROUP_OF_INDIVIDUALS"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("CIVILIAN", "IS_IN_CONTACT_WITH", "TERRORIST_OR_CRIMINAL"),
    ("AGITATING_TROUBLE_MAKING", "HAS_CONSEQUENCE", "BOMBING"),
    ("CIVIL_WAR_OUTBREAK", "INJURED_NUMBER", "QUANTITY_EXACT"),
    ("CIVILIAN", "IS_LOCATED_IN", "PLACE"),
    ("CIVIL_WAR_OUTBREAK", "STARTED_IN", "PLACE"),
    ("MILITARY_ORGANISATION", "IS_AT_ODDS_WITH", "GROUP_OF_INDIVIDUALS"),
    ("EPIDEMIC", "HAS_CONSEQUENCE", "BOMBING"),
    ("CIVILIAN", "INITIATED", "HOOLIGANISM_TROUBLEMAKING"),
    ("TERRORIST_OR_CRIMINAL", "IS_COOPERATING_WITH", "GROUP_OF_INDIVIDUALS"),
    ("GATHERING", "HAS_CONSEQUENCE", "NATURAL_CAUSES_DEATH"),
    ("NON_GOVERNMENTAL_ORGANISATION", "HAS_CONTROL_OVER", "GROUP_OF_INDIVIDUALS"),
    ("MILITARY", "HAS_CONTROL_OVER", "MATERIEL"),
    ("CIVILIAN", "INITIATED", "DEMONSTRATION"),
    ("NON_MILITARY_GOVERNMENT_ORGANISATION", "IS_AT_ODDS_WITH", "CIVILIAN"),
    ("ELECTION", "HAS_CONSEQUENCE", "ELECTION"),
    ("NON_GOVERNMENTAL_ORGANISATION", "START_DATE", "TIME_EXACT"),
    ("GROUP_OF_INDIVIDUALS", "IS_AT_ODDS_WITH", "MILITARY"),
    ("FIRE", "INJURED_NUMBER", "QUANTITY_FUZZY"),
    ("THEFT", "HAS_CONSEQUENCE", "DRUG_OPERATION"),
    ("ACCIDENT", "END_DATE", "TIME_MIN"),
    ("CIVILIAN", "GENDER_FEMALE", "CIVILIAN"),
    ("CIVILIAN", "HAS_CONTROL_OVER", "MATERIEL"),
    ("NON_GOVERNMENTAL_ORGANISATION", "WAS_DISSOLVED_IN", "TIME_EXACT"),
    ("DEMONSTRATION", "END_DATE", "TIME_FUZZY"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "GROUP_OF_INDIVIDUALS"),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "RIOT"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "HOOLIGANISM_TROUBLEMAKING"),
    ("TERRORIST_OR_CRIMINAL", "INITIATED", "SUICIDE"),
    ("GROUP_OF_INDIVIDUALS", "HAS_CONTROL_OVER", "MILITARY_ORGANISATION"),
    ("CRIMINAL_ARREST", "START_DATE", "TIME_FUZZY"),
    ("DEMONSTRATION", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("ILLEGAL_CIVIL_DEMONSTRATION", "HAS_CONSEQUENCE", "RIOT"),
    ("CIVIL_WAR_OUTBREAK", "DEATHS_NUMBER", "QUANTITY_EXACT"),
    ("NON_GOVERNMENTAL_ORGANISATION", "IS_AT_ODDS_WITH", "TERRORIST_OR_CRIMINAL"),
    ("GROUP_OF_INDIVIDUALS", "IS_OF_SIZE", "QUANTITY_MAX"),
    ("FIRE", "START_DATE", "TIME_MIN"),
    ("FIRE", "HAS_CONSEQUENCE", "FIRE"),
    ("HOOLIGANISM_TROUBLEMAKING", "HAS_CONSEQUENCE", "CRIMINAL_ARREST"),
    ("DRUG_OPERATION", "HAS_CONSEQUENCE", "TRAFFICKING"),
    ("GROUP_OF_INDIVIDUALS", "INITIATED", "TRAFFICKING"),
    ("MILITARY", "HAS_CATEGORY", "CATEGORY_0"),
    ("MILITARY", "IS_AT_ODDS_WITH", "TERRORIST_OR_CRIMINAL"),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "AGITATING_TROUBLE_MAKING"),
    ("THEFT", "STARTED_IN", "PLACE"),
    ("CRIMINAL_ARREST", "HAS_CONSEQUENCE", "THEFT"),
    ("ECONOMICAL_CRISIS", "DEATHS_NUMBER", "QUANTITY_FUZZY"),
    ("GATHERING", "HAS_CONSEQUENCE", "CIVIL_WAR_OUTBREAK"),
    ("NATURAL_CAUSES_DEATH", "HAS_CONSEQUENCE", "GATHERING"),
    ("GATHERING", "HAS_CONSEQUENCE", "DEMONSTRATION"),
    ("TERRORIST_OR_CRIMINAL", "HAS_CONTROL_OVER", "CIVILIAN"),
    ("MILITARY", "IS_COOPERATING_WITH", "GROUP_OF_INDIVIDUALS"),
    ("MILITARY_ORGANISATION", "IS_IN_CONTACT_WITH", "CIVILIAN"),
    ("BOMBING", "HAS_CONSEQUENCE", "POLITICAL_VIOLENCE"),
    ("TERRORIST_OR_CRIMINAL", "IS_AT_ODDS_WITH", "INTERGOVERNMENTAL_ORGANISATION"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("ECONOMICAL_CRISIS", "HAS_CONSEQUENCE", "COUP_D_ETAT"),
    ("MILITARY", "INITIATED", "COUP_D_ETAT"),
    ("GATHERING", "END_DATE", "TIME_EXACT"),
    ("STRIKE", "END_DATE", "TIME_EXACT"),
    ("MILITARY", "IS_IN_CONTACT_WITH", "MILITARY"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_IN_CONTACT_WITH",
        "TERRORIST_OR_CRIMINAL",
    ),
    ("COUP_D_ETAT", "STARTED_IN", "PLACE"),
    ("MILITARY", "HAS_CONTROL_OVER", "GROUP_OF_INDIVIDUALS"),
    ("CIVILIAN", "INITIATED", "ILLEGAL_CIVIL_DEMONSTRATION"),
    ("GROUP_OF_INDIVIDUALS", "IS_PART_OF", "MILITARY_ORGANISATION"),
    (
        "NON_MILITARY_GOVERNMENT_ORGANISATION",
        "IS_AT_ODDS_WITH",
        "NON_GOVERNMENTAL_ORGANISATION",
    ),
    ("STRIKE", "HAS_CONSEQUENCE", "STRIKE"),
    ("TRAFFICKING", "START_DATE", "TIME_MAX"),
}


def rebuild_token(token: str, b_offset: int, delimiter="'") -> list:
    """Split and add samples containing unitary tokens.

    Args:
        token (str): _description_
        b_offset (int): _description_
        delimiter (str, optional): _description_. Defaults to "'".

    Returns:
        list: _description_
    """
    corrected_split = []
    subpart = ""
    for char_index, char in enumerate(token):
        if char == delimiter:
            if subpart != "":
                corrected_split += [
                    (
                        subpart,
                        (
                            b_offset
                            if len(corrected_split) == 0
                            else corrected_split[-1][1][1],
                            b_offset + char_index,
                        ),
                    ),
                    (char, (b_offset + char_index, b_offset + char_index + 1)),
                ]
                subpart = ""
            else:
                corrected_split += [
                    (char, (b_offset + char_index, b_offset + char_index + 1)),
                ]
        else:
            subpart += char
    if len(subpart) > 0:
        corrected_split.append(
            (
                subpart,
                (
                    b_offset
                    if len(corrected_split) == 0
                    else corrected_split[-1][1][1],
                    b_offset + char_index + 1,
                ),
            )
        )
    return corrected_split

def word_tokenize(tokens: list) -> list:
    return [
        token.replace("``", '"').replace("''", '"')
        for token in nltk.word_tokenize(tokens, language="french")
    ]

def correct_splitting(text: list, delimiter="'") -> str:
    """Split correctly each tokens given a delimiter of interest.

    Args:
        text (list): _description_
        delimiter (str, optional): _description_. Defaults to "'".

    Returns:
        str: _description_
    """
    corrected_text = []
    for token, (b_offset, e_offset) in text:
        if token == "":
            continue
        if delimiter in token and len(token) > 1:
            corrected_text += rebuild_token(token, b_offset, delimiter)
        else:
            corrected_text.append((token, (b_offset, e_offset)))
    return corrected_text


def word_tokenize(tokens: list) -> list:
    return [
        token.replace("``", '"').replace("''", '"')
        for token in nltk.word_tokenize(tokens, language="french")
    ]


def spans(txt: str) -> (str, (int, int)):
    """Split the text spans.

    Args:
        txt (str): _description_

    Yields:
        _type_: _description_
    """
    tokens = word_tokenize(txt)
    offset = 0
    for token in tokens:
        new_offset = txt.find(token, offset)
        if new_offset - offset > len(token) and token == '"':
            token = "''"
            new_offset = txt.find(token, offset)
        elif new_offset == -1:
            token = "''"
            new_offset = txt.find(token, offset)
        yield token, (new_offset, new_offset + len(token))
        offset = new_offset + len(token)


def get_nltk_tokenization(text: str) -> list:
    """Split the text into words with their offsets.

    Args:
        text (str): text content.

    Returns:
        list: Ordered list of text words with their offsets.
    """
    cleaned_text = correct_splitting(list(spans(text)), "'")
    cleaned_text = correct_splitting(cleaned_text, "-")
    return cleaned_text

def create_directory(d):
    if d and not os.path.exists(d):
        os.makedirs(d)
    return d

def set_seed(args):
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    if args.n_gpu > 0 and torch.cuda.is_available():
        torch.cuda.manual_seed_all(args.seed)


def collate_fn(batch):
    max_len = max([len(f["input_ids"]) for f in batch])
    input_ids = [f["input_ids"] + [0] * (max_len - len(f["input_ids"])) for f in batch]
    input_mask = [[1.0] * len(f["input_ids"]) + [0.0] * (max_len - len(f["input_ids"])) for f in batch]
    labels = [f["labels"] for f in batch]
    entity_pos = [f["entity_pos"] for f in batch]
    hts = [f["hts"] for f in batch]
    input_ids = torch.tensor(input_ids, dtype=torch.long)
    input_mask = torch.tensor(input_mask, dtype=torch.float)
    output = (input_ids, input_mask, labels, entity_pos, hts)
    return output


class PESMSCLApi:
    def __init__(self, args, model_path, device='cuda' if torch.cuda.is_available() else 'cpu'):
        self.device = torch.device(device)
        self.tokenizer = AutoTokenizer.from_pretrained("almanach/camembert-large", local_files_only=True)
        
        
        self.docred_rel2id= json.loads(open("meta/rel2id.json", "r").read())
        self.ner2id = json.loads(open("meta/ner2id.json", "r").read())

        self.id2rel = {value: key for key, value in self.docred_rel2id.items()}
        
        config = AutoConfig.from_pretrained("almanach/camembert-large", local_files_only=True, num_labels=len(self.docred_rel2id.keys()))
        model = AutoModel.from_pretrained("almanach/camembert-large", local_files_only=True, config=config)
        
        config.cls_token_id = self.tokenizer.cls_token_id
        config.sep_token_id = self.tokenizer.sep_token_id
        config.transformer_type = "camembert"
        
        self.model = DocREModel(config, args, model, num_labels=4).to(self.device)
        self.model.load_state_dict(torch.load(model_path, map_location=self.device))
        self.model.eval()
    
    def read_docred(self, data, tokenizer, max_seq_length=1024):
        i_line = 0
        pos_samples = 0
        neg_samples = 0
        features = []
        if data == []:
            return None
        for sample in tqdm(data, desc="Example"):
            sents = []
            sent_map = []
            entities = sample['vertexSet']
            entity_start, entity_end = [], []
            for entity in entities:
                for mention in entity:
                    sent_id = mention["sent_id"]
                    pos = mention["pos"]
                    entity_start.append((sent_id, pos[0],))
                    entity_end.append((sent_id, pos[1] - 1,))
            for i_s, sent in enumerate(sample['sents']):
                new_map = {}
                for i_t, token in enumerate(sent):
                    tokens_wordpiece = tokenizer.tokenize(token)
                    if (i_s, i_t) in entity_start:
                        tokens_wordpiece = ["*"] + tokens_wordpiece
                    if (i_s, i_t) in entity_end:
                        tokens_wordpiece = tokens_wordpiece + ["*"]
                    new_map[i_t] = len(sents)
                    sents.extend(tokens_wordpiece)
                new_map[i_t + 1] = len(sents)
                sent_map.append(new_map)

            train_triple = {}
            if "labels" in sample:
                for label in sample['labels']:
                    evidence = label['evidence']
                    r = int(self.docred_rel2id[label['r']])
                    if (label['h'], label['t']) not in train_triple:
                        train_triple[(label['h'], label['t'])] = [
                            {'relation': r, 'evidence': evidence}]
                    else:
                        train_triple[(label['h'], label['t'])].append(
                            {'relation': r, 'evidence': evidence})

            entity_pos = []
            for e in entities:
                entity_pos.append([])
                for m in e:
                    start = sent_map[m["sent_id"]][m["pos"][0]]
                    end = sent_map[m["sent_id"]][m["pos"][1]]
                    entity_pos[-1].append((start, end,))

            relations, hts = [], []
            for h, t in train_triple.keys():
                relation = [0] * len(self.docred_rel2id)
                for mention in train_triple[h, t]:
                    relation[mention["relation"]] = 1
                    evidence = mention["evidence"]
                relations.append(relation)
                hts.append([h, t])
                pos_samples += 1

            for h in range(len(entities)):
                for t in range(len(entities)):
                    if h != t and [h, t] not in hts:
                        relation = [1] + [0] * (len(self.docred_rel2id) - 1)
                        relations.append(relation)
                        hts.append([h, t])
                        neg_samples += 1

            # assert len(relations) == len(entities) * (len(entities) - 1)

            sents = sents[:max_seq_length - 2]
            input_ids = tokenizer.convert_tokens_to_ids(sents)
            input_ids = tokenizer.build_inputs_with_special_tokens(input_ids)

            i_line += 1
            feature = {'input_ids': input_ids,
                    'entity_pos': entity_pos,
                    'labels': relations,
                    'hts': hts,
                    'title': sample['title'],
                    }
            features.append(feature)

        print("# of documents {}.".format(i_line))
        print("# of positive examples {}.".format(pos_samples))
        print("# of negative examples {}.".format(neg_samples))
        return features
            
    def split_into_sentences(self, tokens):
        sentences = []
        current_sentence = []
        
        for token in tokens:
            current_sentence.append(token)
            
            if token == '.' or token == "?" or token == "!":
                sentences.append(current_sentence)
                current_sentence = []

        if current_sentence:
            sentences.append(current_sentence)

        return sentences
    def find_sent_id(self, start, end, tokenized_sentences):
        count = 0
            
        for i, sent_tokens in enumerate(tokenized_sentences):
            for o in range(len(sent_tokens)):  # +1 for space
                if count == start:
                    j = end - count
                    return i, o, o+j
                count += 1
        return None
    
    def prepare_data_to_docred_format(self, data):
        new_data = {}
        nltk_text = get_nltk_tokenization(data["text"])
        tokens = [token[0] for token in nltk_text]
        sentences = self.split_into_sentences(tokens)
        tokens_list = [word_tokenize(" ".join(sent)) for sent in sentences]
        new_data["sents"] = tokens_list
        new_data["title"] = "id_0"
        list_labels_to_align = json.loads(data["entities"])
        
        labels = []
        for i, mentions_type in enumerate(list_labels_to_align):
            cache_type=str(mentions_type["type"]).upper()
            for i, label in enumerate(mentions_type["mentions"]):

                cache_start = None
                cache_end = None
                start_index = None
                end_index = None
                
                for i, (token, (start, end)) in enumerate(nltk_text):
                    if start >= label['start'] and (start_index is None or i < start_index):
                        start_index = i

                    if end <= label['end'] and (end_index is None or i > end_index):
                        end_index = i

                cache_start = start_index
                cache_end = end_index
                
                sent_id, start, end = self.find_sent_id(cache_start, cache_end, tokens_list)
                labels.append({"name": label["value"], "type": cache_type, "sent_id": sent_id, "pos": [start, end+1], "id":mentions_type["id"]})
            
        sorted_list = sorted(labels, key=lambda x: x['name'])
        vertex_set = [list(group) for _, group in groupby(sorted_list, key=lambda x: x['id'])]
        new_data["vertexSet"] = vertex_set
        new_data["labels"] = []
        return new_data


    
    def prepare(self, data_to_docred):
        data = self.prepare_data_to_docred_format(data_to_docred)
        return self.read_docred([data], self.tokenizer , max_seq_length=1024), data




    def collate_fn(self, batch):
        max_len = max([len(f["input_ids"]) for f in batch])
        titles = [[f["title"]]*len(f["hts"]) for f in batch]
        titles = sum(titles, [])
        input_ids = [f["input_ids"] + [0] * (max_len - len(f["input_ids"])) for f in batch]
        input_mask = [[1.0] * len(f["input_ids"]) + [0.0] * (max_len - len(f["input_ids"])) for f in batch]
        labels = [f["labels"] for f in batch]
        entity_pos = [f["entity_pos"] for f in batch]
        hts = [f["hts"] for f in batch]
        input_ids = torch.tensor(input_ids, dtype=torch.long)
        input_mask = torch.tensor(input_mask, dtype=torch.float)

        assert len(titles) == sum(map(len, hts))
        output = (input_ids, input_mask, labels, entity_pos, hts, titles)
        return output


    def process_predictions(self, pred, features, data):
        results = self.to_official(pred, features)
        
        # Create a mapping from index to entity ID
        dict_to_index = {}
        for j, entity_mentions in enumerate(data['vertexSet']):
            dict_to_index[j] = entity_mentions[0]
        
        # Replace entity indices with entity IDs
        new_results = []
        for i, relation in enumerate(results):
            results[i]["h"] = dict_to_index[relation["h_idx"]]["id"]
            results[i]["t"] = dict_to_index[relation["t_idx"]]["id"]
            if (dict_to_index[relation["h_idx"]]["type"], relation["r"], dict_to_index[relation["t_idx"]]["type"]) in ALLOWED_RELATIONS:    
                new_results.append({"h": dict_to_index[relation["h_idx"]]["id"],"r": relation["r"], "t":dict_to_index[relation["t_idx"]]["id"]})
        
        print(f"Total predictions before filtering: {len(results)}")
        print(f"Total predictions after filtering: {len(new_results)}")
        print(f"Filtered out relations: {len(results)- len(new_results)}")

        # Format results as required
        formatted_results = [[pred["h"], f'"{pred["r"]}"', pred["t"]] for pred in new_results]
        
        return formatted_results
    


    def to_official(self, preds, features):
        h_idx, t_idx, title = [], [], []

        for f in features:
            hts = f["hts"]
            h_idx += [ht[0] for ht in hts]
            t_idx += [ht[1] for ht in hts]
            title += [f["title"] for ht in hts]
        
        res = []
        for i in range(preds.shape[0]):
            pred = preds[i]
            pred = np.nonzero(pred)[0].tolist()
            for p in pred:
                if p != 0:
                    relation = self.id2rel[p]
                    res.append({
                        'title': title[i],
                        'h_idx': h_idx[i],
                        't_idx': t_idx[i],
                        'r': relation,
                    })
        return res

    @torch.no_grad()
    def inference(self, data):
        features, data = self.prepare(data)
        if not features[0]["labels"]:
            return []

        inputs = self.collate_fn(features)
        input_dict = {'input_ids': inputs[0].to(self.device),
                          'attention_mask': inputs[1].to(self.device),
                          'labels': inputs[2],
                          'entity_pos': inputs[3],
                          'hts': inputs[4],   
        }
        
        with torch.no_grad():
            _, pred, logit, _ = self.model(**input_dict)
            logit.cpu().numpy()
            pred = pred.cpu().numpy()
            pred[np.isnan(pred)] = 0
            
        results = self.process_predictions(pred, features, data)
        return results




parser = argparse.ArgumentParser()

parser.add_argument("--data_dir", default="../dataset/docred", type=str)
parser.add_argument("--transformer_type", default="bert", type=str)
parser.add_argument("--model_name_or_path", default="bert-base-cased", type=str)

parser.add_argument("--train_file", default="train_annotated.json", type=str)
parser.add_argument("--dev_file", default="dev.json", type=str)
parser.add_argument("--test_file", default="test.json", type=str)
parser.add_argument("--save_path", default="", type=str)
parser.add_argument("--load_path", default="", type=str)

parser.add_argument("--config_name", default="", type=str,
                    help="Pretrained config name or path if not the same as model_name")
parser.add_argument("--tokenizer_name", default="", type=str,
                    help="Pretrained tokenizer name or path if not the same as model_name")
parser.add_argument("--max_seq_length", default=1024, type=int,
                    help="The maximum total input sequence length after tokenization. Sequences longer "
                            "than this will be truncated, sequences shorter will be padded.")

parser.add_argument("--train_batch_size", default=4, type=int,
                    help="Batch size for training.")
parser.add_argument("--test_batch_size", default=8, type=int,
                    help="Batch size for testing.")
parser.add_argument("--gradient_accumulation_steps", default=1, type=int,
                    help="Number of updates steps to accumulate before performing a backward/update pass.")
parser.add_argument("--num_labels", default=4, type=int,
                    help="Max number of labels in prediction.")
parser.add_argument("--learning_rate", default=5e-5, type=float,
                    help="The initial learning rate for Adam.")
parser.add_argument("--adam_epsilon", default=1e-6, type=float,
                    help="Epsilon for Adam optimizer.")
parser.add_argument("--max_grad_norm", default=1.0, type=float,
                    help="Max gradient norm.")
parser.add_argument("--warmup_ratio", default=0.06, type=float,
                    help="Warm up ratio for Adam.")
parser.add_argument("--num_train_epochs", default=30.0, type=float,
                    help="Total number of training epochs to perform.")
parser.add_argument("--evaluation_steps", default=-1, type=int,
                    help="Number of training steps between evaluations.")
parser.add_argument("--seed", type=int, default=66,
                    help="random seed for initialization")
parser.add_argument("--num_class", type=int, default=97,
                    help="Number of relation types in dataset.")
parser.add_argument("--rel2id", type=str, default="./meta/rel2id.json",
                    help="Number of relation types in dataset.")

parser.add_argument("--ner2id", type=str, default="./meta/ner2id.json",
                    help="Number of entity types in dataset.")
parser.add_argument("--gpu", type=int, default=0,
                    help="GPU ID")
parser.add_argument("--output_dir", type=str, default=None,
                    help="the output dir for saving pretrained model and tokenizer")
parser.add_argument("--tau", default=2.0, type=float, help="tau")
parser.add_argument("--tau_base", default=1.0, type=float, help="tau_base")
parser.add_argument("--lambda_1", default=1.0, type=float, help="lambda_1")
parser.add_argument("--lambda_2", default=1.0, type=float, help="lambda_2")
parser.add_argument("--lambda_3", default=1.0, type=float, help="lambda_3")
parser.add_argument("--sample_ratio", default=1.0, type=float, help="sample_ratio")
args = parser.parse_args()
args.n_gpu = torch.cuda.device_count()
pemscl = PESMSCLApi(args, model_path="/media/data/exps/sylvain/extraction_relations/PEMSCL/checkpoints/popcorn_textmine.pt")
data = []


df = pd.read_csv("/media/data/exps/sylvain/extraction_relations/PEMSCL/dataset/textmine2025/original_data/test.csv", sep=",")
df_sub = pd.DataFrame([], columns=["id", "relations"])    
for i, row in df.iterrows():
    data = {"text": row["text"], "entities": row["entities"]}
    predictions = pemscl.inference(data)
    df_sub = df_sub.append({"id": row['id'], "relations":predictions}, ignore_index=True)

df_sub.to_csv("/media/data/exps/sylvain/extraction_relations/PEMSCL/dataset/textmine2025/original_data/test_submissions_jmrl_pemscl.csv", sep=",", index=False)